{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mp.fullname" . }}-secrets
  labels: {{- include "mp.labels" . | nindent 4 }}
type: Opaque
stringData:
  MASTER_KEY: {{ .Values.secrets.masterKey | quote }}
  MINIO_ACCESS_KEY: {{ .Values.minio.auth.rootUser | quote }}
  MINIO_SECRET_KEY: {{ .Values.minio.auth.rootPassword | quote }}
  BRIDGE_TOKEN: {{ required "secrets.bridgeToken is required" .Values.secrets.bridgeToken | quote }}
{{- if .Values.secrets.licenseServerToken }}
  LICENSE_SERVER_TOKEN: {{ .Values.secrets.licenseServerToken | quote }}
{{- end }}
{{- if .Values.secrets.jwtPrivateKey }}
  jwt_private.pem: |
{{ .Values.secrets.jwtPrivateKey | indent 4 }}
{{- end }}
{{- if .Values.secrets.jwtPublicKey }}
  jwt_public.pem: |
{{ .Values.secrets.jwtPublicKey | indent 4 }}
{{- end }}
{{- end }}
